version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: user_service_db
    env_file: .env  # Load all variables from .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - gov-network
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env  # Load all variables from .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - gov-network
    depends_on:
      - postgres

  user-service:
    build: .
    container_name: user-service              # stable DNS name
#    image: ghaidaaeldsoky/user-service
    env_file: .env  # Load all variables from .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "8082:${SERVER_PORT}"
    networks:
      - gov-network
    depends_on:
      - postgres
      # postgres:
      #   condition: service_healthy

volumes:
  user_postgres_data:  # Unique volume name

networks:
  gov-network:
    external: true